import Head from 'next/head'
import Image from 'next/image'
import { gql, useQuery, useLazyQuery } from '@apollo/client'
import { useState } from 'react'

import AllPets from '../components/AllPets'
import Filter from '../components/Filter'

import styles from '../styles/Home.module.css'


const TOTAL_PETS = gql`
  query TotalPets {
    available: totalPets(status: AVAILABLE)
    checkeOut: totalPets(status: CHECKEDOUT)
    total: totalPets
  }
`

function Home() {
  const [getTotalPets, { data, loading, error }] = useLazyQuery(TOTAL_PETS)
  const [filters, setFilters]= useState({ status: null, category: null});

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error: {error.message}</p>

  const handleChange = (type) => {
    setFilters({...filters, ...type })
  }

  const handleClick = () => {
    getTotalPets()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pet library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Pet library 🐶</h1>
        <div>
          Total Pets: { data?.total } <br />
          Available: { data?.available }<br />
          Checkouted: { data?.checkeOut }<br />
        </div>

        <div>
          <Filter handleChange={handleChange} />
        </div>
        <AllPets {...filters} />

        <button onClick={handleClick}>
          Total Pets
        </button>
      </main>
    </div>
  )
}


export default Home
