import Head from 'next/head'
import { useRouter } from 'next/router'
import { gql, useMutation } from '@apollo/client'
import { useEffect, useRef } from 'react'

import styles from '../styles/Home.module.css'

const LOGIN = gql`
  mutation LogIn($username: ID!, $password: String!) {
    logIn(username: $username password: $password) {
      token
      customer {
        name
      }
    }
  }
`

const LoginPage = () => {
  const router = useRouter()
  const formRef = useRef(null)
  const [loginAccount, { data, loading, error }] = useMutation(LOGIN)

  const handleSubmit = async (e) => {
    e.preventDefault()
    const formData = new FormData(formRef.current)
    // const username = formData.get('username')
    // const password = formData.get('password')

    const form = Object.fromEntries(formData);
    loginAccount({ variables: { ...form } })
  }

  useEffect(() => {
    if (data) {
      localStorage.setItem('token', data.logIn.token)
      if (typeof window !== 'undefined') {
        router.push('/')
      }
    }
  }, [data, router])

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error :(</p>

  return(
    <div className={styles.container}>
      <Head>
        <title>Pet library</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Login Page</h1>

        <form onSubmit={handleSubmit} ref={formRef}>
          <label htmlFor="username">username
            <input type="text" name="username" required placeholder='TYPE HERE'/>
          </label>
          <br />
          <label htmlFor="password">password
            <input type="password" name="password" required placeholder='TYPE HERE'/>
          </label>
          <br />
          <button>
            login
          </button>
        </form>
      </main>
    </div>
  )
}

export default LoginPage
